-- ============================================================================
-- JALI ML - FEATURE ENGINEERING & UNIFIED SCHEMA (SELF-SUSTAINING)
-- ============================================================================
-- Purpose: Continuous, incremental transformation of RAW data into ML Features.

USE DATABASE JALI_ML_DB;
CREATE SCHEMA IF NOT EXISTS FEATURES;

-- Incremental streams for Postgres operational data
CREATE OR REPLACE STREAM RAW.POSTGRES_OVC_STREAM ON TABLE RAW.POSTGRES_OVC_CASES;

-- 2. FEATURE STORE TABLES
-- Materialized tables for high-performance ML training

CREATE TABLE IF NOT EXISTS FEATURES.UNIFIED_ADHERENCE_STORE (
    DISEASE_TYPE VARCHAR,
    PATIENT_ID VARCHAR,
    GENDER VARCHAR,
    AGE_GROUP VARCHAR,
    ADHERENCE_SCORE FLOAT,
    BARRIERS_SCORE FLOAT,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FEATURES.FERTILITY_STORE (
    CLIENTID VARCHAR,
    AGE FLOAT,
    BMI FLOAT,
    CYCLE_LENGTH FLOAT,
    HAS_PEAK_OVULATION INT,
    IS_REGULAR_CYCLE INT,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. AUTOMATED PIPELINE: TASKS
-- These run automatically whenever new data enters the Streams

-- Task for Adherence Features
CREATE OR REPLACE TASK FEATURES.TSK_PROCESS_ADHERENCE
    WAREHOUSE = JALI_ML_WH
    SCHEDULE = '1 MINUTE' -- Frequency of check
    WHEN SYSTEM$STREAM_HAS_DATA('RAW.CRT_STREAM') OR SYSTEM$STREAM_HAS_DATA('RAW.HIV_ADHERENCE_STREAM')
AS
INSERT INTO FEATURES.UNIFIED_ADHERENCE_STORE (DISEASE_TYPE, PATIENT_ID, GENDER, AGE_GROUP, ADHERENCE_SCORE, BARRIERS_SCORE)
SELECT
    'TB', STUDYNUMBER::VARCHAR, GENDER::VARCHAR,
    CASE WHEN AGECAT_CALC = 1 THEN '18-24' ELSE 'Other' END,
    PILLCOUNT, MONITORPROBLEM
FROM RAW.CRT_STREAM;

-- Task for Fertility Features
CREATE OR REPLACE TASK FEATURES.TSK_PROCESS_FERTILITY
    WAREHOUSE = JALI_ML_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('RAW.FEDCYCLE_STREAM')
AS
INSERT INTO FEATURES.FERTILITY_STORE (CLIENTID, AGE, BMI, CYCLE_LENGTH, HAS_PEAK_OVULATION, IS_REGULAR_CYCLE)
SELECT
    CLIENTID, AGE, BMI, LENGTHOFCYCLE, CYCLEWITHPEAKORNOT,
    CASE WHEN LENGTHOFCYCLE BETWEEN 21 AND 35 THEN 1 ELSE 0 END
FROM RAW.FEDCYCLE_STREAM;

-- Task for Live Postgres OVC data
CREATE OR REPLACE TASK FEATURES.TSK_PROCESS_LIVE_OVC
    WAREHOUSE = JALI_ML_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('RAW.POSTGRES_OVC_STREAM')
AS
INSERT INTO FEATURES.UNIFIED_ADHERENCE_STORE (DISEASE_TYPE, PATIENT_ID, GENDER, AGE_GROUP, ADHERENCE_SCORE)
SELECT
    'OVC_LIVE', ovc_id, 'UNKNOWN', 'OVC', 
    CASE WHEN suppression_status = 'Suppressed' THEN 1.0 ELSE 0.0 END
FROM RAW.POSTGRES_OVC_STREAM;

-- 4. START THE AUTOMATION
ALTER TASK FEATURES.TSK_PROCESS_ADHERENCE RESUME;
ALTER TASK FEATURES.TSK_PROCESS_FERTILITY RESUME;
ALTER TASK FEATURES.TSK_PROCESS_LIVE_OVC RESUME;

-- 5. ML READY VIEWS (Pulling from the cleaned Feature Store)
CREATE OR REPLACE VIEW ANALYTICS.ML_UNIFIED_ADHERENCE AS
SELECT * FROM FEATURES.UNIFIED_ADHERENCE_STORE;

CREATE OR REPLACE VIEW ANALYTICS.ML_FERTILITY_PREDICTION AS
SELECT * FROM FEATURES.FERTILITY_STORE;
