// Snowflake SQL Script for Jali AI - Data Ingestion & Analytics Setup

-- 1. DATABASE & WAREHOUSE SETUP
CREATE DATABASE IF NOT EXISTS JALI_ML_DB;
USE DATABASE JALI_ML_DB;

CREATE WAREHOUSE IF NOT EXISTS JALI_ML_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE;

USE WAREHOUSE JALI_ML_WH;

-- 2. SCHEMAS
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS FEATURES;

-- 3. FILE FORMATS & STAGES (IN RAW SCHEMA)
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT RAW.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('', 'NA', 'N/A', 'null', 'NULL', 'None', 'NaN')
    TRIM_SPACE = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE OR REPLACE STAGE RAW.JALI_CSV_STAGE
    FILE_FORMAT = RAW.CSV_FORMAT;

-- 4. TABLE DEFINITIONS

CREATE OR REPLACE TABLE RAW.CRT_DATASET (
    STUDYNUMBER INT, INANALYSIS INT, PROVINCE INT, COUNTYID INT,
    ARM INT, STRATA INT, GENDER INT, AGECAT_CALC INT,
    OCCUPATION_CALC INT, EDUCATIONLEVEL INT, MARRIED_CALC INT,
    RESIDENCE INT, INCOMCAT_CALC INT, DISTTBCL_CALC FLOAT,
    DISTSUPERV_CALC FLOAT, MEDINSUR_CALC INT, SMEARTEST INT,
    OUTCOME_LOSTFUP INT, OUTCOME_POOR INT,
    MISS3DOSE INT, MISS7DOSE INT, PILLCOUNT FLOAT,
    TOTALMISSED_CM FLOAT, TOTALMISSED_PC FLOAT, TOTALMISSED_CM10 FLOAT,
    MONITORPROBLEM INT,
    IM_DOCTOR FLOAT, IM_MEDMON FLOAT, IM_SWITCHED FLOAT,
    DOT_DOCTOR FLOAT, DOT_MEDMON FLOAT, DOT_SWITCHED FLOAT
);

CREATE OR REPLACE TABLE RAW.FEDCYCLEDATA (
    CLIENTID VARCHAR(50), CYCLENUMBER INT, GROUPID INT,
    CYCLEWITHPEAKORNOT INT, REPRODUCTIVECATEGORY INT,
    LENGTHOFCYCLE FLOAT, MEANCYCLELENGTH FLOAT,
    ESTIMATEDDAYOFOVULATION FLOAT, LENGTHOFLUTEALPHASE FLOAT,
    AGE FLOAT, BMI FLOAT
);

CREATE OR REPLACE TABLE RAW.QUALITYOFCARE (
    HEALTH_FACILITY_LEVEL VARCHAR(100), FACILITYTYPE VARCHAR(50),
    AGE FLOAT, SEX VARCHAR(10),
    CD4ATSTART FLOAT, VIRALLOAD VARCHAR(50)
);

CREATE OR REPLACE TABLE RAW.HIV_ADHERENCE_DATASET (
    INCLUDED_CASES VARCHAR(20), UKVSUSA VARCHAR(10),
    AGE_YEARS FLOAT, GENDER VARCHAR(50),
    MARSTOTAL FLOAT, PHQ_TOTAL_AF FLOAT
);

CREATE OR REPLACE TABLE RAW.IMMUNIZATION_SCHEDULE (
    AGE VARCHAR(50),
    VACCINE_NAME VARCHAR(100),
    DOSE VARCHAR(100),
    PREVENTS VARCHAR(500),
    _LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 5. DATA UPLOAD
// Note: Update the file paths below to match where your CSV files are located on your local machine.
PUT 'file://C:/Users/jerem/OneDrive/Desktop/Jali/CRT_dataset.csv' @RAW.JALI_CSV_STAGE/CRT_DATASET/ OVERWRITE=TRUE;
PUT 'file://C:/Users/jerem/OneDrive/Desktop/Jali/FedCycleData.csv' @RAW.JALI_CSV_STAGE/FEDCYCLEDATA/ OVERWRITE=TRUE;
PUT 'file://C:/Users/jerem/OneDrive/Desktop/Jali/QualityOfCare.csv' @RAW.JALI_CSV_STAGE/QUALITYOFCARE/ OVERWRITE=TRUE;
PUT 'file://C:/Users/jerem/OneDrive/Desktop/Jali/HIV_adherence_dataset.csv' @RAW.JALI_CSV_STAGE/HIV_ADHERENCE_DATASET/ OVERWRITE=TRUE;
PUT 'file://C:/Users/jerem/OneDrive/Desktop/Jali/immunization_schedule.csv' @RAW.JALI_CSV_STAGE/IMMUNIZATION_SCHEDULE/ OVERWRITE=TRUE;

-- 6. DATA LOADING 
//// The COPY INTO commands will be executed after the DAG runs, but you can also run them here for initial loading/testing.
COPY INTO RAW.CRT_DATASET FROM @RAW.JALI_CSV_STAGE/CRT_DATASET/ FILE_FORMAT=(FORMAT_NAME=RAW.CSV_FORMAT) ON_ERROR='CONTINUE';
COPY INTO RAW.FEDCYCLEDATA FROM @RAW.JALI_CSV_STAGE/FEDCYCLEDATA/ FILE_FORMAT=(FORMAT_NAME=RAW.CSV_FORMAT) ON_ERROR='CONTINUE';
COPY INTO RAW.QUALITYOFCARE FROM @RAW.JALI_CSV_STAGE/QUALITYOFCARE/ FILE_FORMAT=(FORMAT_NAME=RAW.CSV_FORMAT) ON_ERROR='CONTINUE';
COPY INTO RAW.HIV_ADHERENCE_DATASET FROM @RAW.JALI_CSV_STAGE/HIV_ADHERENCE_DATASET/ FILE_FORMAT=(FORMAT_NAME=RAW.CSV_FORMAT) ON_ERROR='CONTINUE';
COPY INTO RAW.IMMUNIZATION_SCHEDULE FROM @RAW.JALI_CSV_STAGE/IMMUNIZATION_SCHEDULE/ FILE_FORMAT=(FORMAT_NAME=RAW.CSV_FORMAT) ON_ERROR='CONTINUE';

-- 7. BASIC VALIDATION
SELECT 'CRT_DATASET' AS Table_Name, COUNT(*) AS Row_Count FROM RAW.CRT_DATASET
UNION ALL SELECT 'FEDCYCLEDATA', COUNT(*) FROM RAW.FEDCYCLEDATA
UNION ALL SELECT 'QUALITYOFCARE', COUNT(*) FROM RAW.QUALITYOFCARE
UNION ALL SELECT 'HIV_ADHERENCE', COUNT(*) FROM RAW.HIV_ADHERENCE_DATASET
UNION ALL SELECT 'IMMUNIZATION', COUNT(*) FROM RAW.IMMUNIZATION_SCHEDULE;

-- 8. ML ANALYTICS VIEW - IMMUNIZATION
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW ANALYTICS.ML_IMMUNIZATION_SCHEDULE AS
SELECT 
    VACCINE_NAME,
    AGE AS AGE_LABEL,
    CASE 
        WHEN AGE = 'Birth' THEN 0
        WHEN AGE = '6 Weeks' THEN 42
        WHEN AGE = '10 Weeks' THEN 70
        WHEN AGE = '14 Weeks' THEN 98
        WHEN AGE = '6 Months' THEN 182
        WHEN AGE = '7 Months' THEN 212
        WHEN AGE = '9 Months' THEN 273
        WHEN AGE = '12 Months' THEN 365
        WHEN AGE = '18 Months' THEN 547
        WHEN AGE = '2 Years' THEN 730
        ELSE NULL 
    END AS DUE_DAYS_FROM_BIRTH,
    DOSE,
    PREVENTS
FROM RAW.IMMUNIZATION_SCHEDULE;
